version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank_cards_db
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rk.rdtyysqvjhc98
    ports:
      - "15432:5432"  # Меняем внешний порт на 15432
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bank_cards_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Rk.rdtyysqvjhc98
    ports:
      - "8080:8080"

volumes:
  db-data:
